# Generated by Django 4.0.2 on 2022-02-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('oil_level', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ignition', models.BooleanField()),
                ('fuel_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_stamp', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.UniqueConstraint(fields=('time_stamp', 'item_id', 'company_id'), name='unique_item_value'),
        ),
    ]
