# Generated by Django 4.0.2 on 2022-02-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monitor',
            name='unique_item_value',
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.UniqueConstraint(fields=('time_stamp', 'item', 'company'), name='unique_item_value'),
        ),
    ]
