# Generated by Django 4.0.2 on 2022-03-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_monitor_unique_item_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='ignition',
            field=models.BooleanField(null=True),
        ),
    ]
