# Generated by Django 4.0.2 on 2022-03-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_monitor_ignition'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='doors',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
